[project]
name = "fastapi-mongo-app"
version = "0.1.0"
description = "FastAPI + MongoDB Example"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pymongo",
    "python-dotenv",
    "pydantic",
    "pydantic[email]",   # 👈 add this
    "pytest",
    "httpx"
]

[tool.pytest.ini_options]
pythonpath = ["."]
