name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGO_URL: mongodb://localhost:27017/testdb

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/fastapi-mongo-app:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/fastapi-mongo-app:latest
